AllCops:
  Exclude:
    - 'config/initializers/**/*'
    - 'config/environments/**/*'
    - 'config/puma.rb'
    - 'db/**/**/'
    - 'bin/bundle'
    - 'node_modules/**/*'
    - 'bin/yarn'
    - Berksfile
    - recipes/basic.rb
    - attributes/*.rb

# Customize rules
Metrics/LineLength:
  Max: 120

MethodLength:
  Max: 35

Metrics/AbcSize:
  Enabled: false

BlockLength:
  Max: 70

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Documentation:
  Enabled: false
